//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.14 at 03:40:52 PM NZST 
//


package com.nullendpoint;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.com.sixtree.xref.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class RelationFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.com.sixtree.xref.model
     * 
     */
    public RelationFactory() {
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public static Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Relation.Reference }
     * @param id 
     * 
     */
    public static Relation.Reference createRelationReference(int id, String endpoint, String endpointId) {
        Relation.Reference reference = new Relation.Reference();
        reference.setId(id);
        reference.setEndpoint(endpoint);
        reference.setEndpointId(endpointId);
        return reference;
    }

	public static Relation.Reference createRelationReference(String endpoint, String endpointId) {
        Relation.Reference reference = new Relation.Reference();
		reference.setEndpoint(endpoint);
		reference.setEndpointId(endpointId);
		return reference;
	}

}
