@startuml
systemFoo -> Integration: endpoint:systemFoo id:foo123 entity:person
activate Integration
Integration -> XrefId: Do we have an existing Id in the system? \nGET "/xref/companya/person?endpoint=systemFoo&id=foo123"
activate XrefId
XrefId -> XrefId: lookup (found Id)
XrefId -> Integration : HTTP 200 OK \n {"commonId": "f1e8dbd5-ab30-46e5-9503-6c2c105d45ef", \n"references": [\n    {"endpoint": "systemFoo", "endpointId": "foo123"} \n] }
deactivate XrefId
Integration -> XrefId: Find out the id to interact with systemBar \nGET "/xref/companya/person/f1e8dbd5-ab30-46e5-9503-6c2c105d45ef"
activate XrefId
XrefId -> XrefId: getRelation
XrefId -> Integration: 200 OK \n{"commonId": "f1e8dbd5-ab30-46e5-9503-6c2c105d45ef", \n "references": [ \n    {"endpoint": "systemFoo", "endpointId": "foo123"}, \n    {"endpoint": "systemBar", "endpointId": "bar123"} \n  ] \n}
deactivate XrefId
Integration -> systemBar: interactWithPerson(id="bar123")
activate systemBar
systemBar -> systemBar: interactWithPerson(id="bar123")
systemBar -> Integration: 200 OK
deactivate systemBar
deactivate XrefId
deactivate Integration
@enduml