CREATE SCHEMA XREF;
CREATE TABLE IF NOT EXISTS XREF.`ENTITYTYPE`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ENTITYTYPE` VARCHAR(45) NOT NULL,
  `TENANT` VARCHAR(45) NOT NULL);

CREATE INDEX XREF.ENTITYTYPE_0 ON XREF.`ENTITYTYPE` (`ENTITYTYPE` ASC);
CREATE INDEX XREF.TENANT_0 ON XREF.`ENTITYTYPE` (`TENANT` ASC,`ENTITYTYPE` ASC);

CREATE TABLE IF NOT EXISTS XREF.`RELATION`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `COMMONID` VARCHAR(45) NOT NULL,
  `ENTITYTYPE_ID` INT NOT NULL
);

CREATE INDEX XREF.COMMONID_0 ON XREF.`RELATION` (`COMMONID` ASC);
CREATE INDEX XREF.FK_RELATION_ENTITYTYPE1_IDX_0 ON XREF.`RELATION` (`ENTITYTYPE_ID` ASC);


CREATE TABLE IF NOT EXISTS XREF.`REFERENCE`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `RELATION_ID` INT NOT NULL,
  `ENDPOINT` VARCHAR(45) NOT NULL,
  `ENDPOINTID` VARCHAR(45) NOT NULL);

CREATE INDEX XREF.FK_REFERENCE_RELATION_IDX_0 ON XREF.`REFERENCE` (`RELATION_ID` ASC);
CREATE INDEX XREF.ENDPOINT_0 ON XREF.`REFERENCE` (`ENDPOINTID` ASC);


ALTER TABLE XREF.`RELATION`
  ADD FOREIGN KEY (`ENTITYTYPE_ID`)
REFERENCES XREF.`ENTITYTYPE`(`ID`);


ALTER TABLE XREF.`REFERENCE`
  ADD FOREIGN KEY (`RELATION_ID`)
REFERENCES XREF.`RELATION`(`ID`);