CREATE TABLE IF NOT EXISTS `ENTITYTYPE`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `ENTITYTYPE` VARCHAR(45) NOT NULL,
  `TENANT` VARCHAR(45) NOT NULL);

-- CREATE INDEX ENTITYTYPE_0 ON `ENTITYTYPE` (`ENTITYTYPE` ASC);
-- CREATE INDEX TENANT_0 ON `ENTITYTYPE` (`TENANT` ASC,`ENTITYTYPE` ASC);

CREATE TABLE IF NOT EXISTS `RELATION`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `COMMONID` VARCHAR(45) NOT NULL,
  `ENTITYTYPE_ID` INT NOT NULL
);

-- CREATE INDEX IF NOT EXISTS COMMONID_0 ON `RELATION` (`COMMONID` ASC);
-- CREATE INDEX IF NOT EXISTS FK_RELATION_ENTITYTYPE1_IDX_0 ON `RELATION` (`ENTITYTYPE_ID` ASC);


CREATE TABLE IF NOT EXISTS `REFERENCE`
(`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `RELATION_ID` INT NOT NULL,
  `ENDPOINT` VARCHAR(45) NOT NULL,
  `ENDPOINTID` VARCHAR(45) NOT NULL);

-- CREATE INDEX IF NOT EXISTS FK_REFERENCE_RELATION_IDX_0 ON `REFERENCE` (`RELATION_ID` ASC);
-- CREATE INDEX IF NOT EXISTS ENDPOINT_0 ON `REFERENCE` (`ENDPOINTID` ASC);


-- ALTER TABLE `RELATION`
--   ADD FOREIGN KEY (`ENTITYTYPE_ID`)
-- REFERENCES `ENTITYTYPE`(`ID`);
--
--
-- ALTER TABLE `REFERENCE`
--   ADD FOREIGN KEY (`RELATION_ID`)
-- REFERENCES `RELATION`(`ID`);